// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPXe7KeUS7CZ9kCltJcFOSrOGyJa75a7U',
    appId: '1:748413725398:web:eac552ce017ae8a8367777',
    messagingSenderId: '748413725398',
    projectId: 'chat-f2347',
    authDomain: 'chat-f2347.firebaseapp.com',
    storageBucket: 'chat-f2347.firebasestorage.app',
    measurementId: 'G-MQMYTMQPHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2XyamsIgYF3JRYzYFZ4miifu6T2LyQ1s',
    appId: '1:748413725398:android:fa1b046be2cf7862367777',
    messagingSenderId: '748413725398',
    projectId: 'chat-f2347',
    storageBucket: 'chat-f2347.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWYXj9VVJCBSyO5IJcbnD68rNwg4r92ho',
    appId: '1:748413725398:ios:828078308fa52721367777',
    messagingSenderId: '748413725398',
    projectId: 'chat-f2347',
    storageBucket: 'chat-f2347.firebasestorage.app',
    androidClientId: '748413725398-gd5sj9odl45m4g81sea7ij61f741536n.apps.googleusercontent.com',
    iosClientId: '748413725398-nj2u9rqe0r00d9tdtmg416ccqurmedi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWYXj9VVJCBSyO5IJcbnD68rNwg4r92ho',
    appId: '1:748413725398:ios:828078308fa52721367777',
    messagingSenderId: '748413725398',
    projectId: 'chat-f2347',
    storageBucket: 'chat-f2347.firebasestorage.app',
    androidClientId: '748413725398-gd5sj9odl45m4g81sea7ij61f741536n.apps.googleusercontent.com',
    iosClientId: '748413725398-nj2u9rqe0r00d9tdtmg416ccqurmedi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPXe7KeUS7CZ9kCltJcFOSrOGyJa75a7U',
    appId: '1:748413725398:web:b8f4b9d8e153df1c367777',
    messagingSenderId: '748413725398',
    projectId: 'chat-f2347',
    authDomain: 'chat-f2347.firebaseapp.com',
    storageBucket: 'chat-f2347.firebasestorage.app',
    measurementId: 'G-WX0M64Q2JJ',
  );
}
